export const Users = [
    {
        id: 1,
        profilePicture: "assets/person/1.jpeg",
        username: "Mirco Rossi",
    },
    {
        id: 2,
        profilePicture: "assets/person/2.jpeg",
        username: "Gianluca Bertolotti",
    },
    {
        id: 3,
        profilePicture: "assets/person/3.jpeg",
        username: "Emanuele Mariani Cerati",
    },
    {
        id: 4,
        profilePicture: "assets/person/4.jpeg",
        username: "Anna Bonassi",
    },
    {
        id: 5,
        profilePicture: "assets/person/5.jpeg",
        username: "Mauro Bonassi",
    },
    {
        id: 6,
        profilePicture: "assets/person/6.jpeg",
        username: "Pietro Ferrari",
    },
    {
        id: 7,
        profilePicture: "assets/person/7.jpeg",
        username: "Debora Pradella",
    },
    {
        id: 8,
        profilePicture: "assets/person/8.jpeg",
        username: "Nicholas Zagni",
    },
    {
        id: 9,
        profilePicture: "assets/person/9.jpeg",
        username: "Lorenzo Torreggiani",
    },
    {
        id: 10,
        profilePicture: "assets/person/10.jpeg",
        username: "Ester Bonassi",
    },
];

export const Posts = [
    {
        id: 1,
        description: "Love for all, hatred for none",
        photo: "assets/post/1.jpeg",
        date: "5 min ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        description: "That was my fault.",
        photo: "assets/post/2.jpeg",
        date: "15 min ago",
        userId: 2,
        like: 16,
        comment: 9,
    },
    {
        id: 3,
        description: "I can't tell you how much meant to all of us",
        photo: "assets/post/3.jpeg",
        date: "25 min ago",
        userId: 3,
        like: 8,
        comment: 9,
    },
    {
        id: 4,
        description: "I loved the way you handled that",
        photo: "assets/post/4.jpeg",
        date: "35 min ago",
        userId: 4,
        like: 4,
        comment: 9,
    },
    {
        id: 5,
        description: "Can I get your advice on this?",
        photo: "assets/post/5.jpeg",
        date: "45 min ago",
        userId: 5,
        like: 2,
        comment: 9,
    },
    {
        id: 6,
        description: "I'm happy to see you!",
        photo: "assets/post/6.jpeg",
        date: "55 min ago",
        userId: 6,
        like: 1,
        comment: 9,
    },
    {
        id: 7,
        description: "I trust your judgment",
        photo: "assets/post/7.jpeg",
        date: "65 min ago",
        userId: 7,
        like: 2,
        comment: 9,
    },
    {
        id: 8,
        description: "What was the highlight of your day (or week)?",
        photo: "assets/post/8.jpeg",
        date: "75 min ago",
        userId: 8,
        like: 4,
        comment: 9,
    },
    {
        id: 9,
        photo: "assets/post/9.jpeg",
        date: "85 min ago",
        userId: 9,
        like: 8,
        comment: 9,
    },
    {
        id: 10,
        photo: "assets/post/10.jpeg",
        date: "95 min ago",
        userId: 10,
        like: 16,
        comment: 9,
    },
]
